version: "3.9"

services:
  sbc-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    networks:
      - sbc-net

  sbc-client:
    build: ./client/
    depends_on:
      - sbc-server
    ports:
      - "3000:3000"
    networks:
      - sbc-net

  sbc-server:
    build: ./server/
    depends_on:
      - sbc-db
    ports:
      - "4567:4567"
    environment:
      PORT: ${PORT}
      DATABASE_URL: postgresql://${PG_USER}:${PG_PASSWORD}@sbc-db:5432/${PG_DB}?schema=public
    command: >
      bash -c "npm run p-migrate-deploy && npm start"
    networks:
      - sbc-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/reload-cert.sh:/docker-entrypoint.d/reload-cert.sh:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --standalone --non-interactive --email psapsa190@gmail.com --agree-tos --preferred-challenges http --dry-run -d sbc.pyaesoneaung.com -d www.sbc.pyaesoneaung.com
    networks:
      - sbc-net

  cret-renew:
    container_name: certnew
    build:
      context: .
      dockerfile: ./certbot/renew/dockerfile
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  sbc-net:
    driver: bridge
