version: "3.9"

services:
  sbc-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    networks:
      - sbc-net

  sbc-client:
    build: ./client/
    depends_on:
      - sbc-server
    networks:
      - sbc-net

  sbc-server:
    build: ./server/
    depends_on:
      - sbc-db
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - sbc-net

networks:
  sbc-net:
    driver: bridge
