version: "3.3"

services:
  psql:
    image: postgres
    restart: always
    container_name: "sdb_psql"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
