FROM certbot/certbot:latest


COPY ./cert-renew-crontab /etc/crontabs/cert-renew-crontab

RUN chmod 0644 /etc/crontabs/cert-renew-crontab && crontab /etc/crontabs/cert-renew-crontab

ENTRYPOINT ["crond", "-f"]

